[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 1000
evm_version = "paris"
gas_limit = 25000000
gas_price = 1000000000
gas_reports = ["*"]

[rpc_endpoints]
filecoin-calibration = "https://api.calibration.node.glif.io/rpc/v1"
filecoin-mainnet = "https://api.node.glif.io/rpc/v1"

# Filecoin Calibration Configuration
[profile.calibration]
chain_id = 314159
eth_rpc_url = "https://api.calibration.node.glif.io/rpc/v1"
